// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpqioistwhphcaihjbdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwcWlvaXN0d2hwaGNhaWhqYmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMjM4MzAsImV4cCI6MjA1NDc5OTgzMH0.RnL8iNvbFnaaG7o_3ZiF-UC9ELqZ0x23Yz5xyUAEZa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);